# Generated by Django 5.1.4 on 2025-05-07 21:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0020_alter_detilsreservation_datelivraison_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='client',
            new_name='ville',
        ),
        migrations.AlterField(
            model_name='cabinesautonome',
            name='refMateriel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventaire.stock'),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 21, 57, 24, 222950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 21, 57, 24, 222950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='refMateriel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventaire.stock'),
        ),
        migrations.AlterField(
            model_name='modulaire',
            name='refMateriel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventaire.stock'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='refMateriel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.stock'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 21, 57, 24, 221943, tzinfo=datetime.timezone.utc)),
        ),
    ]
