# Generated by Django 5.1.4 on 2025-05-10 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0021_rename_client_stock_ville_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 5, 10, 18, 45, 7, 296744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 5, 10, 18, 45, 7, 296744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 5, 10, 18, 45, 7, 295804, tzinfo=datetime.timezone.utc)),
        ),
    ]
