# Generated by Django 5.1.4 on 2025-05-10 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0022_alter_detilsreservation_datelivraison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='client',
        ),
        migrations.AddField(
            model_name='movement',
            name='ville',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 5, 10, 18, 51, 37, 261747, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 5, 10, 18, 51, 37, 261747, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='movement',
            name='lieu',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 5, 10, 18, 51, 37, 260750, tzinfo=datetime.timezone.utc)),
        ),
    ]
